### PR TITLE
Feature/unshared memory (Work in progress)

### PR DESCRIPTION
**Pull request by v1kko**
Unshare data structures, one by one

### CODE REVIEW

**Comment by TijnBerends** [comment]
Please try to stick to the notation standards of the rest of the model. Particularly, Fortran keywords are written in all caps (e.g. ALLOCATABLE, POINTER, INTEGER, IF, WHILE, etc.).

**Comment by v1kko** [comment]
@TijnBerends Thanks for pointing that out, I will write a conversion script before this work is done that can convert all the keywords to UPPERCASE (my pinkies don't like it when I write ALLCAPS all day) to adhere to the standards of the code.

**Comment by TijnBerends** [comment]
Also, just to check: are you waiting for me to merge this?

**Comment by v1kko** [comment]
No, I converted it to a draft, I think we should only merge it after its finished/testing (might take a while)

**Pull request merged**
